name: "CI"
on: "push"

jobs:
  Lint:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Deno"
        uses: denoland/setup-deno@v1

      - name: "Lint Code"
        run: "deno task ci:lint"

  Check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Deno"
        uses: denoland/setup-deno@v1

      # Because this is a library with only exports, no code will actually "run"
      # However, this will make Deno analyze it and make sure everything is OK.
      - name: "Check Code"
        run: "deno run mod.ts"

  Publish:
    runs-on: "ubuntu-latest"
    needs: [Lint, Build]
    concurrency: "npm"

    environment:
      name: "NPM"
      url: "https://www.npmjs.com/package/@httpcord/rest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Setup Deno"
        uses: denoland/setup-deno@v1

      - name: "Setup Node.JS"
        uses: actions/setup-node@v2
        with: { node-version: "16" }

      - name: "Transform Code"
        run: "deno task ci:transform ${{ github.sha }}"

      - name: "Publish to NPM"
        env: { NPM_TOKEN: "${{ secrets.NPM_TOKEN }}" }
        run: |
          cd npm
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish --access public
